### PR TITLE
Update to derive_more v1.0

### PR DESCRIPTION
**Pull request by jayvdb**

### CODE REVIEW

**Comment by ndmitchell** [comment]
See starlark_syntax/src/codemap.rs line 694. I'd be shocked if that line wasn't the root cause.

Note that internally at Meta we try and all share the same version of derive_more with a monorepo. That means this change, which will require corresponding updates to every user of derive_more, might take a little while to merge upstream. Your contribution is appreciated though, makes it a lot easier for us.

**Comment by ndmitchell** [comment]
From https://github.com/JelteF/derive_more/blob/master/CHANGELOG.md#breaking-changes

> The Display derive (and other fmt-like ones) now uses #[display("...", (<expr>),*)] syntax instead of #[display(fmt = "...", ("<expr>"),*)], and #[display(bound(<bound>))] instead of #[display(bound = "<bound>")]. So without the double quotes around the expressions and bounds.

So seems you will have to take everything which has quotes in the non-first arguments of display and remove the quotes.

**Comment by jayvdb** [comment]
All tests now pass locally. No worries about how long it takes.

**Comment by ndmitchell** [comment]
I've done this internally using your patch. Probably take a few days to get outside, as it required upgrading quite a bit. But in progress. Thanks for your help!

**Pull request closed without merging**
