### PR TITLE
Fix missing comma in Stmt::Load Display impl

### PR DESCRIPTION
**Pull request by rossdylan**
I was exploring using starlark_syntax to merge BUILD files together, and noticed that it generates invalid load statements. Its a simple fix, we just add a comma that was missing from the Display impl.

This is the same as #131 just from my work github org so the CLA automation works correctly.

### CODE REVIEW

**Comment by stepancheg** [comment]
Looks good. Can you sign CLA please?

**Comment by rossdylan** [comment]
> Looks good. Can you sign CLA please?

Thanks! Working on that, I need to figure out how to get this covered by the existing CLA my company has signed

**Comment by rossdylan** [comment]
I'll fix the tests that expect the invalid output too

**Comment by stepancheg** [comment]
Thanks!

**Pull request closed without merging**
